### PR TITLE
fix bug No codesigning certificates found, #49 && #16

### PR DESCRIPTION
**Pull request by DavidWanderer**

### CODE REVIEW

**Comment by DanTheMan827** [comment]
what is the difference between codesigning and appleid?

I've never had any issues with code signing aside from the occasional time where I'll end up with an expired certificate next to my valid one.

**Comment by josegonzalez** [comment]
This also appears to not have output for me but has output when switching to the value specified in the PR. Not sure what might happen if I switch as I'm using the built version and haven't recompiled this.

**Comment by DavidWanderer** [comment]
> what is the difference between codesigning and appleid?
> 
> I've never had any issues with code signing aside from the occasional time where I'll end up with an expired certificate next to my valid one.

Indeed, in most cases, a valid certificate can be found, but I did encounter a situation where the certificate cannot be found.

**Comment by MHarlock** [comment]
same issue

**Comment by DanTheMan827** [comment]
@DavidWanderer Do you know if this still works with older versions of macOS?

**Comment by alannzi** [comment]
>

**Review by lafi-99 — APPROVED** [review]

**Comment by DavidWanderer** [comment]
> @DavidWanderer Do you know if this still works with older versions of macOS?

Yes, it  still works with older versions of macOS.

**Review by Zef1628 — APPROVED** [review]

**Review by Zef1628 — APPROVED** [review]

**Review by Zef1628 — APPROVED** [review]
#``

**Comment by jirikrepl** [comment]
this helped me:
https://help.twixlmedia.com/hc/en-us/articles/115000790705-iOS-Manage-signing-certificates-for-your-apps

1. Launch Xcode
2. Go to the Preferences...
3. Select the Account tab
4. Select your account
5. Select the appropriate Team and click on Manage Certificates... (Note that Distribution certificates belong to the team but only the Account Holder or Admin role can create distribution certificates. If you’re enrolled as an individual, you are the Account Holder).
6. Click on the + icon and select the type of certificate you need, depending on the Build Type. For more info about Build Types, [see this article](https://twixlmedia.zendesk.com/hc/en-us/articles/115000790845-ios-app-build-types).
    Xcode will do the signing request, get and download the certificate and add it to your Keychain! We told you we made it easier!
5fcd1a56-85fe-45a6-8e3f-75c912b4e5e4

**Comment by ColonelXing** [comment]
来信已收到！我会尽快回复。

**Pull request merged**
